[project]
name = "news-stream-recommender"
version = "0.1.0"
description = ""
authors = [
    {name = "Jah-Wilson Teeba",email = "therealjwil07@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.121.1,<0.122.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "pymongo (>=4.15.4,<5.0.0)",
    "pyopenssl (>=25.3.0,<26.0.0)",
    "cryptography (>=46.0.3,<47.0.0)",
    "certifi (>=2024.12.14,<2025.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
